# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BOM_Check.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BOM_Check(object):
    def setupUi(self, BOM_Check):
        BOM_Check.setObjectName("BOM_Check")
        BOM_Check.resize(668, 861)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BOM_Check.sizePolicy().hasHeightForWidth())
        BOM_Check.setSizePolicy(sizePolicy)
        BOM_Check.setMaximumSize(QtCore.QSize(668, 861))
        BOM_Check.setStyleSheet("background-color: rgb(43, 45, 48);")
        self.centralwidget = QtWidgets.QWidget(BOM_Check)
        self.centralwidget.setObjectName("centralwidget")
        self.BOM_Check_2 = QtWidgets.QLabel(self.centralwidget)
        self.BOM_Check_2.setGeometry(QtCore.QRect(1, 0, 661, 51))
        self.BOM_Check_2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.BOM_Check_2.setStyleSheet("background-color: rgb(30, 31, 34);\n"
"font: 63 italic 24pt \"Adobe Hebrew\";\n"
"color: rgb(195, 195, 195);")
        self.BOM_Check_2.setAlignment(QtCore.Qt.AlignCenter)
        self.BOM_Check_2.setObjectName("BOM_Check_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(200, 60, 461, 751))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setStyleSheet("background-color: rgb(41, 44, 45);\n"
"font: 63 11pt \"Bahnschrift SemiBold\";\n"
"color: rgb(209, 209, 209);\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(186, 60, 20, 751))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 50, 671, 21))
        self.line_2.setStyleSheet("background-color: rgb(84, 84, 84);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(10)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 810, 661, 21))
        self.label_2.setStyleSheet("background-color: rgb(30, 31, 34);")
        self.label_2.setObjectName("label_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(650, 50, 20, 761))
        self.line_3.setStyleSheet("background-color: rgb(90, 90, 90);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(10)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.BOM1 = QtWidgets.QPushButton(self.centralwidget)
        self.BOM1.setGeometry(QtCore.QRect(10, 80, 161, 71))
        self.BOM1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOM1.setStyleSheet("background-color: rgb(31, 34, 35);\n"
"color: rgb(175, 175, 175);\n"
"font: 15pt \"Algerian\";")
        self.BOM1.setObjectName("BOM1")
        self.BOM2 = QtWidgets.QPushButton(self.centralwidget)
        self.BOM2.setGeometry(QtCore.QRect(10, 190, 161, 71))
        self.BOM2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOM2.setStyleSheet("color: rgb(175, 175, 175);\n"
"background-color: rgb(31, 34, 35);\n"
"font: 15pt \"Algerian\";")
        self.BOM2.setObjectName("BOM2")
        self.START = QtWidgets.QPushButton(self.centralwidget)
        self.START.setGeometry(QtCore.QRect(10, 300, 161, 71))
        self.START.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.START.setStyleSheet("color: rgb(175, 175, 175);\n"
"background-color: rgb(31, 34, 35);\n"
"font: 15pt \"Algerian\";")
        self.START.setObjectName("START")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 810, 671, 21))
        self.line_4.setStyleSheet("background-color: rgb(84, 84, 84);")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(10)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.CLOSE = QtWidgets.QPushButton(self.centralwidget)
        self.CLOSE.setGeometry(QtCore.QRect(10, 740, 161, 71))
        self.CLOSE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CLOSE.setStyleSheet("color: rgb(175, 175, 175);\n"
"background-color: rgb(31, 34, 35);\n"
"font: 15pt \"Algerian\";")
        self.CLOSE.setObjectName("CLOSE")
        self.CLEAR = QtWidgets.QPushButton(self.centralwidget)
        self.CLEAR.setGeometry(QtCore.QRect(10, 410, 161, 71))
        self.CLEAR.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CLEAR.setStyleSheet("color: rgb(175, 175, 175);\n"
"background-color: rgb(31, 34, 35);\n"
"font: 15pt \"Algerian\";")
        self.CLEAR.setObjectName("CLEAR")
        self.DEMO = QtWidgets.QPushButton(self.centralwidget)
        self.DEMO.setGeometry(QtCore.QRect(10, 520, 161, 71))
        self.DEMO.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DEMO.setStyleSheet("color: rgb(175, 175, 175);\n"
"background-color: rgb(31, 34, 35);\n"
"font: 15pt \"Algerian\";")
        self.DEMO.setObjectName("DEMO")
        self.MESSAGE = QtWidgets.QPushButton(self.centralwidget)
        self.MESSAGE.setGeometry(QtCore.QRect(10, 630, 161, 71))
        self.MESSAGE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MESSAGE.setStyleSheet("color: rgb(175, 175, 175);\n"
"background-color: rgb(31, 34, 35);\n"
"font: 15pt \"Algerian\";")
        self.MESSAGE.setObjectName("MESSAGE")
        self.line_4.raise_()
        self.line_3.raise_()
        self.line_2.raise_()
        self.line.raise_()
        self.BOM_Check_2.raise_()
        self.textBrowser.raise_()
        self.label_2.raise_()
        self.BOM1.raise_()
        self.BOM2.raise_()
        self.START.raise_()
        self.CLOSE.raise_()
        self.CLEAR.raise_()
        self.DEMO.raise_()
        self.MESSAGE.raise_()
        BOM_Check.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BOM_Check)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 26))
        self.menubar.setObjectName("menubar")
        BOM_Check.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BOM_Check)
        self.statusbar.setObjectName("statusbar")
        BOM_Check.setStatusBar(self.statusbar)

        self.retranslateUi(BOM_Check)
        self.CLOSE.clicked.connect(BOM_Check.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BOM_Check)

    def retranslateUi(self, BOM_Check):
        _translate = QtCore.QCoreApplication.translate
        BOM_Check.setWindowTitle(_translate("BOM_Check", "BOM_Check"))
        self.BOM_Check_2.setText(_translate("BOM_Check", "BOM_Check"))
        self.label_2.setText(_translate("BOM_Check", "TextLabel"))
        self.BOM1.setText(_translate("BOM_Check", "加载BOM1"))
        self.BOM2.setText(_translate("BOM_Check", "加载BOM2"))
        self.START.setText(_translate("BOM_Check", "开始比对"))
        self.CLOSE.setText(_translate("BOM_Check", "关闭"))
        self.CLEAR.setText(_translate("BOM_Check", "清除"))
        self.DEMO.setText(_translate("BOM_Check", "BOM模版"))
        self.MESSAGE.setText(_translate("BOM_Check", "使用说明"))
