# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BOM_Check.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pandas as pd
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QMainWindow,QTextBrowser, QFileDialog
import sys
import requests

# 下载线程（防止界面卡死）
class DownloadThread(QtCore.QThread):
    progress = QtCore.pyqtSignal(int)
    finished = QtCore.pyqtSignal(str)
    error = QtCore.pyqtSignal(str)

    def __init__(self, url, save_path):
        super().__init__()
        self.url = url
        self.save_path = save_path

    def run(self):
        try:
            resp = requests.get(self.url, stream=True, timeout=30)
            resp.raise_for_status()
            total_size = int(resp.headers.get('content-length', 0))

            with open(self.save_path, 'wb') as f:
                downloaded = 0
                for chunk in resp.iter_content(chunk_size=1024*1024):
                    if chunk:
                        f.write(chunk)
                        downloaded += len(chunk)
                        if total_size > 0:
                            percent = int((downloaded / total_size) * 100)
                            self.progress.emit(percent)
            self.finished.emit(self.save_path)
        except Exception as e:
            self.error.emit(str(e))


class Ui_BOM_Check(object):
    def setupUi(self, BOM_Check):
        BOM_Check.setObjectName("BOM_Check")
        BOM_Check.resize(668, 861)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BOM_Check.sizePolicy().hasHeightForWidth())
        BOM_Check.setSizePolicy(sizePolicy)
        BOM_Check.setMaximumSize(QtCore.QSize(668, 861))
        BOM_Check.setStyleSheet("background-color: rgb(43, 45, 48);")
        self.centralwidget = QtWidgets.QWidget(BOM_Check)
        self.centralwidget.setObjectName("centralwidget")
        self.BOM_Check_2 = QtWidgets.QLabel(self.centralwidget)
        self.BOM_Check_2.setGeometry(QtCore.QRect(1, 0, 661, 51))
        self.BOM_Check_2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.BOM_Check_2.setStyleSheet("background-color: rgb(30, 31, 34);\n"
"font: 63 italic 24pt \"Adobe Hebrew\";\n"
"color: rgb(195, 195, 195);")
        self.BOM_Check_2.setAlignment(QtCore.Qt.AlignCenter)
        self.BOM_Check_2.setObjectName("BOM_Check_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(200, 60, 461, 751))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setStyleSheet("background-color: rgb(41, 44, 45);\n"
"font: 63 11pt \"Bahnschrift SemiBold\";\n"
"color: rgb(209, 209, 209);\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(186, 60, 20, 751))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 50, 671, 21))
        self.line_2.setStyleSheet("background-color: rgb(84, 84, 84);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(10)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 810, 661, 21))
        self.label_2.setStyleSheet("background-color: rgb(30, 31, 34);")
        self.label_2.setObjectName("label_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(650, 50, 20, 761))
        self.line_3.setStyleSheet("background-color: rgb(90, 90, 90);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(10)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.BOM1 = QtWidgets.QPushButton(self.centralwidget)
        self.BOM1.setGeometry(QtCore.QRect(10, 80, 161, 71))
        self.BOM1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOM1.setStyleSheet("background-color: rgb(31, 34, 35);\n"
"color: rgb(175, 175, 175);\n"
"font: 15pt \"Algerian\";")
        self.BOM1.setObjectName("BOM1")
        self.BOM2 = QtWidgets.QPushButton(self.centralwidget)
        self.BOM2.setGeometry(QtCore.QRect(10, 190, 161, 71))
        self.BOM2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BOM2.setStyleSheet("color: rgb(175, 175, 175);\n"
"background-color: rgb(31, 34, 35);\n"
"font: 15pt \"Algerian\";")
        self.BOM2.setObjectName("BOM2")
        self.START = QtWidgets.QPushButton(self.centralwidget)
        self.START.setGeometry(QtCore.QRect(10, 300, 161, 71))
        self.START.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.START.setStyleSheet("color: rgb(175, 175, 175);\n"
"background-color: rgb(31, 34, 35);\n"
"font: 15pt \"Algerian\";")
        self.START.setObjectName("START")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 810, 671, 21))
        self.line_4.setStyleSheet("background-color: rgb(84, 84, 84);")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(10)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.CLOSE = QtWidgets.QPushButton(self.centralwidget)
        self.CLOSE.setGeometry(QtCore.QRect(10, 740, 161, 71))
        self.CLOSE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CLOSE.setStyleSheet("color: rgb(175, 175, 175);\n"
"background-color: rgb(31, 34, 35);\n"
"font: 15pt \"Algerian\";")
        self.CLOSE.setObjectName("CLOSE")
        self.CLEAR = QtWidgets.QPushButton(self.centralwidget)
        self.CLEAR.setGeometry(QtCore.QRect(10, 410, 161, 71))
        self.CLEAR.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CLEAR.setStyleSheet("color: rgb(175, 175, 175);\n"
"background-color: rgb(31, 34, 35);\n"
"font: 15pt \"Algerian\";")
        self.CLEAR.setObjectName("CLEAR")
        self.DEMO = QtWidgets.QPushButton(self.centralwidget)
        self.DEMO.setGeometry(QtCore.QRect(10, 520, 161, 71))
        self.DEMO.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DEMO.setStyleSheet("color: rgb(175, 175, 175);\n"
"background-color: rgb(31, 34, 35);\n"
"font: 15pt \"Algerian\";")
        self.DEMO.setObjectName("DEMO")
        self.MESSAGE = QtWidgets.QPushButton(self.centralwidget)
        self.MESSAGE.setGeometry(QtCore.QRect(10, 630, 161, 71))
        self.MESSAGE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MESSAGE.setStyleSheet("color: rgb(175, 175, 175);\n"
"background-color: rgb(31, 34, 35);\n"
"font: 15pt \"Algerian\";")
        self.MESSAGE.setObjectName("MESSAGE")
        self.line_4.raise_()
        self.line_3.raise_()
        self.line_2.raise_()
        self.line.raise_()
        self.BOM_Check_2.raise_()
        self.textBrowser.raise_()
        self.label_2.raise_()
        self.BOM1.raise_()
        self.BOM2.raise_()
        self.START.raise_()
        self.CLOSE.raise_()
        self.CLEAR.raise_()
        self.DEMO.raise_()
        self.MESSAGE.raise_()
        BOM_Check.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BOM_Check)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 26))
        self.menubar.setObjectName("menubar")
        BOM_Check.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BOM_Check)
        self.statusbar.setObjectName("statusbar")
        BOM_Check.setStatusBar(self.statusbar)

        self.retranslateUi(BOM_Check)
        self.CLOSE.clicked.connect(BOM_Check.close) # type: ignore
        self.BOM1.clicked.connect(self.load_BOM1)
        self.BOM2.clicked.connect(self.load_BOM2)
        self.START.clicked.connect(self.start_bom)
        self.CLEAR.clicked.connect(self.clear_all)
        self.MESSAGE.clicked.connect(self.information)
        self.DEMO.clicked.connect(self.demo_bom)
        QtCore.QMetaObject.connectSlotsByName(BOM_Check)

        # 用来保存读取后的表格
        self.df1 = None
        self.df2 = None

        self.big_list1 = list()
        self.big_list2 = list()
        self.download_thread = None

    def retranslateUi(self, BOM_Check):
        _translate = QtCore.QCoreApplication.translate
        BOM_Check.setWindowTitle(_translate("BOM_Check", "BOM_Check"))
        self.BOM_Check_2.setText(_translate("BOM_Check", "BOM_Check"))
        self.label_2.setText(_translate("BOM_Check", "BOM_Check V1.0 By 2026 03 28 MZC"))
        self.BOM1.setText(_translate("BOM_Check", "加载BOM1"))
        self.BOM2.setText(_translate("BOM_Check", "加载BOM2"))
        self.START.setText(_translate("BOM_Check", "开始比对"))
        self.CLOSE.setText(_translate("BOM_Check", "关闭"))
        self.CLEAR.setText(_translate("BOM_Check", "清除"))
        self.DEMO.setText(_translate("BOM_Check", "BOM模版"))
        self.MESSAGE.setText(_translate("BOM_Check", "使用说明"))

    def load_BOM1(self):
        # 弹出文件选择框，只显示 Excel
        file_path, _ = QFileDialog.getOpenFileName(None,"选择BOM1文件","","Excel Files (*.xlsx *.xls)")
        if not file_path:
            return
        try:
            self.textBrowser.insertPlainText('加载BOM1\n')
            print('加载BOM1:')
            self.df1=pd.read_excel(file_path, sheet_name='材料清单', usecols=['Quantity', 'Reference'])
            self.textBrowser.insertPlainText('BOM1加载成功\n')
            self.textBrowser.insertPlainText(file_path + "\n")
            self.quantity_list1 = self.df1['Quantity']
            self.reference_list1 = self.df1['Reference'].tolist()
        except Exception as e:
            self.textBrowser.insertPlainText(f"BOM1 加载失败: {e}\n")

    def load_BOM2(self):
        # 弹出文件选择框，只显示 Excel
        file_path2, _ = QFileDialog.getOpenFileName(None, "选择BOM2文件", "", "Excel Files (*.xlsx *.xls)")
        if not file_path2:
            return
        try:
            self.textBrowser.insertPlainText('加载BOM2\n')
            print('加载BOM2:')
            self.df2 = pd.read_excel(file_path2,sheet_name='材料清单', usecols=['Quantity', 'Reference'])
            self.textBrowser.insertPlainText('BOM2加载成功\n')
            self.textBrowser.insertPlainText(file_path2 + "\n")
            self.quantity_list2 = self.df2['Quantity']
            self.reference_list2 = self.df2['Reference'].tolist()
        except Exception as e:
            self.textBrowser.insertPlainText(f"BOM2 加载失败: {e}\n")

    def demo_bom(self):
        # ====================== 下载 BOM 模版功能 ======================
        self.textBrowser.insertPlainText("\n📥 准备下载 BOM 模版文件...")

        # 在这里替换成你的真实模版下载链接
        demo_url = "https://raw.githubusercontent.com/mygithubma/BOM_Check/main/demo_bom.xlsx"

        save_path, _ = QFileDialog.getSaveFileName(None, "保存BOM模版", "BOM模版.xlsx", "Excel Files (*.xlsx)")
        if not save_path:
            self.textBrowser.insertPlainText("已取消下载\n")
            return

        self.DEMO.setEnabled(False)
        self.DEMO.setText("下载中...")

        self.download_thread = DownloadThread(demo_url, save_path)
        self.download_thread.progress.connect(lambda p: self.textBrowser.insertPlainText(f"下载进度：{p}%\r"))
        self.download_thread.finished.connect(self.demo_done)
        self.download_thread.error.connect(self.demo_error)
        self.download_thread.start()

    def demo_done(self, path):
        self.DEMO.setEnabled(True)
        self.DEMO.setText("BOM模版")
        self.textBrowser.append(f"\n✅ 下载完成！\n保存路径：{path}\n")
        # QMessageBox.information(None, "成功", "BOM模版下载完成！")

    def demo_error(self, msg):
        self.DEMO.setEnabled(True)
        self.DEMO.setText("BOM模版")
        self.textBrowser.append(f"\n❌ 下载失败：{msg}\n")
        # QMessageBox.critical(None, "失败", f"下载失败：{msg}")

    def information(self):
        self.textBrowser.insertPlainText("\n")
        self.textBrowser.insertPlainText("请确保BOM的sheet页存在名为材料清单的页\n")
        self.textBrowser.insertPlainText("并且名为材料清单的页中有标签为['Quantity', 'Reference']的列\n")
        self.textBrowser.insertPlainText("\n")


    def clear_all(self):
        """清空文本框 + 清空加载的Excel数据"""
        # 清空界面显示
        self.textBrowser.clear()

        # 清空加载的文件
        self.df1 = None
        self.df2 = None
        self.quantity_list1=[]
        self.quantity_list2 = []
        self.reference_list1=[]
        self.reference_list2 = []
        self.first_list1 = 0
        self.first_list2 = 0
        self.second_list1 =0
        self.second_list2 = 0
        self.big_list1 = []
        self.big_list2 = []
        # 提示
        self.textBrowser.append("🧹 已清空所有数据！\n")


    def start_bom(self):
        if len(self.reference_list1) == len(self.reference_list2):
            self.textBrowser.insertPlainText("\n")
            self.textBrowser.insertPlainText("两个BOM行数相同\n")
            # print('BOM1')
            num = len(self.reference_list1)
            self.textBrowser.insertPlainText(f'BOM共有{str(num)}行\n')
            # print('原BOM1')
            # print(reference_list1)
            self.textBrowser.insertPlainText(f'BOM1共有 {sum(self.quantity_list1)}个器件\n')
            # print('原BOM2')
            # print(reference_list2)
            self.textBrowser.insertPlainText(f'BOM2共有{sum(self.quantity_list2)}个器件\n')
            self.textBrowser.insertPlainText('\n')
            # print(reference_list2)

            if sum(self.quantity_list1) != sum(self.quantity_list2):
                self.textBrowser.insertPlainText('BOM1和BOM2元器件总数量不同，请检查BOM\n\n')
                for i in range(len(self.reference_list1)):
                    self.first_list1 = self.reference_list1[i].split(',')
                    for j in range(len(self.first_list1)):
                        self.second_list1 = self.first_list1[j].split(',')
                        self.big_list1.extend(self.second_list1)
                for i2 in range(len(self.reference_list2)):
                    self.first_list2 = self.reference_list2[i2].split(',')
                    # print(first_list)
                    for j2 in range(len(self.first_list2)):
                        self.second_list2 = self.first_list2[j2].split(',')
                        # print(second_list)
                        self.big_list2.extend(self.second_list2)

            else:
                self.textBrowser.insertPlainText('BOM1和BOM2元器件总数量相同，请检查BOM\n\n')
                for i in range(len(self.reference_list1)):
                    self.first_list1 = self.reference_list1[i].split(',')
                    for j in range(len(self.first_list1)):
                        self.second_list1 = self.first_list1[j].split(',')
                        self.big_list1.extend(self.second_list1)
                for i2 in range(len(self.reference_list2)):
                    self.first_list2 = self.reference_list2[i2].split(',')
                    # print(first_list)
                    for j2 in range(len(self.first_list2)):
                        self.second_list2 = self.first_list2[j2].split(',')
                        # print(second_list)
                        self.big_list2.extend(self.second_list2)

                # print(big_list1)
                # print(self.big_list1)
                # print(self.big_list2)
            self.textBrowser.insertPlainText(f'第一个BOM共有{len(self.big_list1)}个\n')
            if len(set(self.big_list1)) != len(self.big_list1):
                self.textBrowser.insertPlainText("BOM1中有重复值！\n")
                self.duplicates1 = list({x for x in self.big_list1 if self.big_list1.count(x) > 1})
                self.textBrowser.insertPlainText(f'BOM1中重复位号：{self.duplicates1}\n\n')

            else:
                self.textBrowser.insertPlainText("BOM1没有重复值")
            self.textBrowser.insertPlainText('\n')

                # print(big_list2)
            self.textBrowser.insertPlainText(f'第二个BOM共有{len(self.big_list2)}个\n')
            if len(set(self.big_list2)) != len(self.big_list2):
                self.textBrowser.insertPlainText("BOM2中有重复值！\n")
                self.duplicates2 = list({x for x in self.big_list2 if self.big_list2.count(x) > 1})
                self.textBrowser.insertPlainText(f'BOM2中重复位号：{self.duplicates2}\n')
            else:
                self.textBrowser.insertPlainText("BOM2没有重复值\n")
            self.textBrowser.insertPlainText('\n')

            self.diff1 = [x for x in self.big_list1 if x not in self.big_list2]
            self.diff2 = [x for x in self.big_list2 if x not in self.big_list1]
            if len(self.diff1) != 0:
                self.textBrowser.insertPlainText('在BOM1但是不在BOM2的位号\n')
                self.textBrowser.insertPlainText(f'{self.diff1}共{len(self.diff1)}个\n')
                df = pd.DataFrame(self.diff1, columns=["在BOM1但是不在BOM2的位号"])  # columns 是表头
                df.to_excel("在BOM1但是不在BOM2的位号.xlsx", index=False)
            else:
                self.textBrowser.insertPlainText('BOM1中的位号都在BOM2中\n')
            if len(self.diff2) != 0:
                self.textBrowser.insertPlainText('在BOM2但是不在BOM1的位号')
                self.textBrowser.insertPlainText(f'{self.diff2}共{len(self.diff2)}个\n')
                df = pd.DataFrame(self.diff2, columns=["在BOM2但是不在BOM1的位号"])  # columns 是表头
                df.to_excel("在BOM2但是不在BOM1的位号.xlsx", index=False)
            else:
                self.textBrowser.insertPlainText('BOM2中的位号都在BOM1中\n')

        else:
            self.textBrowser.insertPlainText('\n')
            self.textBrowser.insertPlainText("两个BOM行数不同,请检查BOM\n")
            self.textBrowser.insertPlainText(f'BOM1行数：{len(self.quantity_list1)}\n')
            self.textBrowser.insertPlainText(f'BOM2行数：{len(self.quantity_list2)}\n')
            self.textBrowser.insertPlainText(f'BOM1共有{sum(self.quantity_list1)}个器件\n')
            # print('原BOM2')
            # print(reference_list2)
            self.textBrowser.insertPlainText(f'BOM2共有{sum(self.quantity_list2)}个器件\n')
            self.textBrowser.insertPlainText('\n')
            # print(reference_list2)

            if sum(self.quantity_list1) != sum(self.quantity_list2):
                self.textBrowser.insertPlainText('BOM1和BOM2元器件总数量不同，请检查BOM\n')
                for i in range(len(self.reference_list1)):
                    self.first_list1 = self.reference_list1[i].split(',')
                    for j in range(len(self.first_list1)):
                        self.second_list1 = self.first_list1[j].split(',')
                        self.big_list1.extend(self.second_list1)
                for i2 in range(len(self.reference_list2)):
                    self.first_list2 = self.reference_list2[i2].split(',')
                    # print(first_list)
                    for j2 in range(len(self.first_list2)):
                        self.second_list2 = self.first_list2[j2].split(',')
                        self.big_list2.extend(self.second_list2)
            else:
                self.textBrowser.insertPlainText('BOM1和BOM2元器件总数量相同，请检查BOM\n\n')
                for i in range(len(self.reference_list1)):
                    self.first_list1 = self.reference_list1[i].split(',')
                    for j in range(len(self.first_list1)):
                        self.second_list1 = self.first_list1[j].split(',')
                        self.big_list1.extend(self.second_list1)
                for i2 in range(len(self.reference_list2)):
                    self.first_list2 = self.reference_list2[i2].split(',')
                    # print(first_list)
                    for j2 in range(len(self.first_list2)):
                        self.second_list2 = self.first_list2[j2].split(',')
                        # print(second_list)
                        self.big_list2.extend(self.second_list2)
                # print(big_list1)
            self.textBrowser.insertPlainText(f'第一个BOM共有{len(self.big_list1)}个位号\n')
            if len(set(self.big_list1)) != len(self.big_list1):
                self.textBrowser.insertPlainText("BOM1中有重复值！")
                self.duplicates1 = list({x for x in self.big_list1 if self.big_list1.count(x) > 1})
                self.textBrowser.insertPlainText(f'BOM1中重复位号:{self.duplicates1}\n')
            else:
                self.textBrowser.insertPlainText("BOM1没有重复值\n")
            self.textBrowser.insertPlainText('\n')

                # print(big_list2)
            self.textBrowser.insertPlainText(f'第二个BOM共有{len(self.big_list2)}个位号\n')
            if len(set(self.big_list2)) != len(self.big_list2):
                self.textBrowser.insertPlainText("BOM2中有重复值！\n")
                self.duplicates2 = list({x for x in self.big_list2 if self.big_list2.count(x) > 1})
                self.textBrowser.insertPlainText(f'BOM2中重复位号：{self.duplicates2}\n')
            else:
                self.textBrowser.insertPlainText("BOM2没有重复值\n")
            self.textBrowser.insertPlainText('\n')

            self.diff1 = [x for x in self.big_list1 if x not in self.big_list2]
            self.diff2 = [x for x in self.big_list2 if x not in self.big_list1]
            if len(self.diff1) != 0:
                self.textBrowser.insertPlainText('在BOM1但是不在BOM2的位号')
                self.textBrowser.insertPlainText(f'{self.diff1}共{len(self.diff1)}个\n')
                df = pd.DataFrame(self.diff1, columns=["在BOM1但是不在BOM2的位号"])  # columns 是表头
                df.to_excel("在BOM1但是不在BOM2的位号.xlsx", index=False)
            else:
                self.textBrowser.insertPlainText('BOM1中的位号都在BOM2中\n')
            if len(self.diff2) != 0:
                self.textBrowser.insertPlainText('在BOM2但是不在BOM1的位号')
                self.textBrowser.insertPlainText(f'{self.diff2}共{len(self.diff2)}个\n')
                df = pd.DataFrame(self.diff2, columns=["在BOM2但是不在BOM1的位号"])  # columns 是表头
                df.to_excel("在BOM2但是不在BOM1的位号.xlsx", index=False)
            else:
                self.textBrowser.insertPlainText('BOM2中的位号都在BOM1中\n')


if __name__ == '__main__':
    # 只有直接运行这个脚本，才会往下执行
    # 别的脚本文件执行，不会调用这个条件句

    # 实例化，传参
    app = QApplication(sys.argv)

    # 创建对象
    mainWindow = QMainWindow()

    # 创建ui，引用demo1文件中的Ui_MainWindow类
    ui = Ui_BOM_Check()
    # 调用Ui_MainWindow类的setupUi，创建初始组件
    ui.setupUi(mainWindow)
    # 创建窗口
    mainWindow.show()
    # 进入程序的主循环，并通过exit函数确保主循环安全结束(该释放资源的一定要释放)
    sys.exit(app.exec_())